### ISSUE TITLE
Dataset Issue

### ISSUE THREAD

**Issue by yhzhu99** [ZhiGroup/CovRNN#4]
How to get access of the Cerner Covid dataset used in this paper? I cannot find the link in cerner's page. Can your team share the download link or related methods to get access the dataset? Thanks!

**Comment by lrasmy** [comment]
Hi Yinghao,

The Cerner RWD Covid-19 dataset, is owned by Cerner and hosted on Cerner HealtheDataLab as described in our paper. It is not a downloadable dataset, and since March 2021, as far as I know, free access is not granted unless your institution is a part of the Cerner Learning Health Network. You may need to check with Cerner to learn more.
Here is the link: https://www.cerner.com/solutions/real-world-data

Thanks,
Laila
