### ISSUE TITLE
question about the representation of missing data in the model

### ISSUE THREAD

**Issue by yekaizhou** [ZhiGroup/CovRNN#5]
Hi developers,

I am interested in the role of missing data in the training & use of your model.

Is the missing data in the time series remains NA in your RNN model, or was replaced with value 0, as you illustrated in your workflow?

Thanks,
Yekai

**Comment by lrasmy** [comment]
Hi Yekai,

All our data is in categorical format, so either the patient had the event at certain visit or not. That also include laboratory results, for example "blood glucose level high". Then we use embeddings to represent those categorical variables, so in this sense we do not worry about the missing data. In other words, if we use one hot representation, if the patient had the event at a certain time, that will have 1 otherwise it is a 0.

Hope this answers your question.

Thanks,
Laila

**Comment by yekaizhou** [comment]
Dear Laila,

Thanks a lot for your reply!

And may I know how do you categorize the continuous lab results? Are they manually determined from clinicians' experience and medical criteria, or these threshold to determine "blood glucose level high or low" are selected by AI algorithms?

Thanks,
Yekai

**Comment by lrasmy** [comment]
Hi Yekai,

for the lab results, we categorize based on the data source. For example, the Cerner RWD results table have an interpretation column, that reflects the lab specialist categorization of the result, if it is normal, above normal, critically high, low ... etc, so we mostly utilize this. On the other hand the Optum data, only had the upper and lower limit associated with the lab result, so we used these limits to categorize the results. if for any reason, the exact result category is not clear, we just use the lab test name to reflect that this lab was ordered.

Hopefully that helps.

Thanks,
Laila

**Comment by yekaizhou** [comment]
Thanks a lot Laila for your detailed explanations!
